[package]
name = "witnet_data_structures"
version = "0.1.0"
authors = ["Witnet Foundation <info@witnet.foundation>"]
workspace = ".."
description = "data structures component"
edition = "2018"
build = "build.rs"

[dependencies]
flatbuffers = "0.4.0"
